### ISSUE TITLE
Remove brackets in method name

### ISSUE THREAD

**Issue by piotrekjanus** [magierska/cheatsheetGenerator#18]
I would like to use your generator for pipeR cheatsheet. The problem is, that I need to introduce `%>>%` operator. I tried to use parameter `methods` but it creates bracket at the end of method name, so it looks like `%>>%()`. Do you have any idea how can I overcome my problem?

**Comment by szymanskir** [comment]
A new version with an additional parameter `withoutBrackets` has been added. Please refer to the example in the documentation.
